#!/bin/bash

if [[ "$INITSYSTEM" == "on" ]]; then
	#Set the root password as root if not set as an ENV variable
	export PASSWD=${PASSWD:=root}
	#Set the root password
	echo "root:$PASSWD" | chpasswd
  	echo "RUNNING"
  	dropbear -REm -p 22
  	/opt/hangoutsbot/hangupsbot/hangupsbot.py --config /data/hangoutsbot/config.json --cookies /data/hangoutsbot/cookies.json --memory /data/hangoutsbot/memory.json
else
	#Set the root password as root if not set as an ENV variable
	export PASSWD=${PASSWD:=root}
	#Set the root password
	echo "root:$PASSWD" | chpasswd
	echo "RUNNING"
	dropbear -REm -p 22
	/opt/hangoutsbot/hangupsbot/hangupsbot.py --config /data/hangoutsbot/config.json --cookies /data/hangoutsbot/cookies.json --memory /data/hangoutsbot/memory.json
fi

while true
do
	echo "App exited but container is still running to allow web terminal access"
	#Set the root password as root if not set as an ENV variable
	export PASSWD=${PASSWD:=root}
	#Set the root password
	echo "root:$PASSWD" | chpasswd
	dropbear -REm -p 22
	sleep 3600
done
